"""Renderer for the equilibrium-set track: reads CSV, writes equilibrium_set.pdf and tables.md.

It never solves, never changes a parameter, and never drops a row. Lines connect only adjacent rows of
the dense grid in entry_band.csv; the dead branch is drawn at zero across the plotted range.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[3]))

from numerics.render.style import (DASHED, DOTTED, FULL_WIDTH, GRAY, INK, MUTED, NAVY, RUST, SOLID,  # noqa: E402
                                   TINT_C, label_line, panel_label, plt)


def read(name: str) -> list[dict]:
    with (HERE / name).open() as fh:
        return list(csv.DictReader(fh))


def col(rows: list[dict], key: str) -> np.ndarray:
    return np.array([float(r[key]) for r in rows])


def figure() -> None:
    band = read("entry_band.csv")
    r = col(band, "r")
    e_hi, e_lo = col(band, "E_minimal_pool"), col(band, "E_least_z_eq_n")
    n_r, z_u = col(band, "n_r"), col(band, "z_U")
    r_e, r_c, fr = float(band[0]["r_e"]), float(band[0]["r_C"]), float(band[0]["frak_r_k"])
    cert = {row["name"]: row for row in read("certificates.csv")}
    r_j = 0.5 * (float(cert["r_J: (1-1/b) J(r_J) = k"]["lo"]) + float(cert["r_J: (1-1/b) J(r_J) = k"]["hi"]))

    fig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(FULL_WIDTH, 2.7))
    lo, hi = 1.0, 3.8
    ax_a.fill_between(r, e_lo, e_hi, color=TINT_C, lw=0)
    ax_a.plot(r, e_hi, color=NAVY, ls=SOLID)
    ax_a.plot(r, e_lo, color=RUST, ls=DASHED)
    ax_a.plot([lo, hi], [0, 0], color=GRAY, ls=SOLID, lw=1.2)
    for x in (r_e, r_j, r_c):
        ax_a.axvline(x, color=MUTED, ls=DOTTED, lw=0.8)
    ax_a.axvspan(lo, fr, color="#e9edf5", lw=0)
    ax_a.set_xlim(lo, hi)
    ax_a.set_ylim(-0.02, 0.45)
    ax_a.set_xlabel(r"incumbent strength $r$")
    ax_a.set_ylabel(r"entry $\mathsf{E}$")
    label_line(ax_a, 2.6, float(np.interp(2.6, r, e_hi)), "minimal pool", NAVY, dy=3)
    label_line(ax_a, 3.0, float(np.interp(3.0, r, e_lo)), "least entry", RUST, dy=5)
    label_line(ax_a, 2.6, 0.0, r"dead $\mathcal{D}$", GRAY, dy=3)
    for x, t in ((r_e, r"$r_e$"), (r_j, r"$r_J$"), (r_c, r"$r_C$")):
        ax_a.text(x, 0.44, t, ha="center", va="top", fontsize=8, color=MUTED,
                  bbox=dict(facecolor="white", edgecolor="none", pad=0.5))
    panel_label(ax_a, "(a)")

    ax_b.fill_between(r, n_r, z_u, color=TINT_C, lw=0)
    ax_b.plot(r, z_u, color=NAVY, ls=SOLID)
    ax_b.plot(r, n_r, color=RUST, ls=DASHED)
    for x in (r_e, r_j, r_c):
        ax_b.axvline(x, color=MUTED, ls=DOTTED, lw=0.8)
    ax_b.set_xlim(lo, hi)
    ax_b.set_ylim(0, 1.05)
    ax_b.set_xlabel(r"incumbent strength $r$")
    ax_b.set_ylabel(r"low-type order magnitude $z=-q_L$")
    label_line(ax_b, 1.75, float(np.interp(1.75, r, z_u)), r"$z_U(r)$", NAVY, dx=-4, ha="right")
    label_line(ax_b, 2.6, float(np.interp(2.6, r, n_r)), r"$n(r)$", RUST, dy=-12)
    panel_label(ax_b, "(b)")
    fig.tight_layout()
    fig.savefig(HERE / "equilibrium_set.pdf")


def fmt(x: str, d: int = 4) -> str:
    try:
        v = float(x)
    except ValueError:
        return x
    return f"{v:.{d}f}" if abs(v) >= 1e-3 or v == 0 else f"{v:.2e}"


def table(rows: list[dict], keys: list[tuple[str, str]], d: int = 4) -> str:
    head = "| " + " | ".join(h for _, h in keys) + " |\n|" + "---|" * len(keys) + "\n"
    body = "".join("| " + " | ".join(fmt(r[k], d) for k, _ in keys) + " |\n" for r in rows)
    return head + body


def tables() -> None:
    out = ["# Tables for the equilibrium-set track\n", "Generated by `render.py` from the CSV files. Do not edit by hand.\n"]
    cert = read("certificates.csv")
    out.append("\n## T1. Interval certificates (`certificates.csv`)\n\n")
    out.append("| quantity | lower | upper | proves | holds | status |\n|---|---|---|---|---|---|\n")
    out.extend(f"| {c['name']} | {c['lo']} | {c['hi']} | {c['statement']} | {c['holds']} | {c['status']} |\n" for c in cert)
    br = read("live_branch.csv")
    keep = [b for b in br if b["r"] in {"1.658590825", "1.658600825", "1.66", "1.7", "1.75", "1.8", "1.85", "1.9",
                                         "1.95", "2", "2.015516441", "2.05", "2.1", "2.5", "3", "3.5", "3.59"}]
    out.append("\n## T2. Minimal-pool live branch with $q_H=1$ (`live_branch.csv`)\n\n")
    out.append(table(keep, [("r", "$r$"), ("qL", "$q_L$"), ("x_star", "$x^*$"), ("E", "$\\mathsf E$"), ("O_H", "$\\mathsf O_H$"),
                            ("U_H", "$U_H$"), ("U_L", "$U_L$"), ("H_gap_U(1)-maxU", "$U_H(1)-\\max U_H$"),
                            ("dPsi_dz", "$\\partial_z\\Psi$")]))
    reg = read("full_order_region.csv")
    keep = [x for x in reg if x["r"] in {"1.8", "2", "2.014516441", "2.015416441", "2.015616441", "2.016516441",
                                          "2.05", "3", "3.5", "3.592657519"}]
    out.append("\n## T3. Global optimality of full orders against the minimal pool (`full_order_region.csv`)\n\n")
    out.append(table(keep, [("r", "$r$"), ("test_(1-1/b)J-k", "$(1-1/b)J-k$"), ("gap_H_U(1)-maxU", "$U_H(1)-\\max U_H$"),
                            ("gap_L_U(-1)-maxU", "$U_L(-1)-\\max U_L$"), ("argmax_L", "low type's best order"),
                            ("slope_U_L_at_1_backward_difference", "slope of $U_L$ at 1"), ("equilibrium", "equilibrium")], d=6))
    below = read("below_edge.csv")
    keep = below[::7] + below[-5:]
    out.append("\n## T4. Below the edge: the low type's marginal profit at its own order (`below_edge.csv`)\n\n")
    out.append(table(keep, [("r", "$r$"), ("n_r", "$n(r)$"), ("max_Psi", "$\\max_z\\Psi$"), ("argmax_z", "argmax $z$"),
                            ("max_BR_minus_z", "$\\max_z(\\mathrm{BR}(z)-z)$"), ("live_with_qH_1", "live")], d=6))
    holes = read("holes_r3.csv")
    out.append("\n## T5. Entry sets with holes at $r=3$, full orders (`holes_r3.csv`)\n\n")
    out.append(table(holes, [("entry_set", "entry set $A$"), ("E", "$\\mathsf E$"), ("J_A", "$J_A$"),
                             ("test_(1-1/b)J_A-k", "$(1-1/b)J_A-k$"), ("H_best", "H best"), ("L_best", "L best"),
                             ("pool_posterior", "$\\bar\\mu_N$"), ("equilibrium", "equilibrium")]))
    rng = read("holes_range.csv")
    out.append("\n## T6. Entry range over full-order equilibria (`holes_range.csv`)\n\n")
    out.append(table(rng[::4] + [rng[-1]], [("r", "$r$"), ("E_max_minimal_pool", "max $\\mathsf E$"),
                                            ("E_min_any_entry_set", "min $\\mathsf E$, any $A$"),
                                            ("least_entry_set_upper_end_y", "$y$ in $[x^*,y]$"),
                                            ("E_min_cutoff_family", "min $\\mathsf E$, cutoff family")]))
    zr = read("z_range.csv")
    out.append("\n## T7. Low-type orders that some entry set supports, cutoff representatives (`z_range.csv`)\n\n")
    out.append(table(zr, [("r", "$r$"), ("z", "$z$"), ("cutoff_x'", "$x'$"), ("E", "$\\mathsf E$"), ("U_H", "$U_H$"),
                          ("U_L", "$U_L$"), ("H_best", "H best"), ("L_dev", "L best $+z$"), ("equilibrium", "equilibrium")]))
    le = read("least_entry.csv")
    out.append("\n## T8. Least-entry set $[x^*(z),y]$ for each supported $z$ (`least_entry.csv`)\n\n")
    out.append(table(le, [("r", "$r$"), ("z", "$z$"), ("x_star", "$x^*$"), ("y", "$y$"), ("E_least", "least $\\mathsf E$"),
                          ("H_best", "H best"), ("L_dev", "L best $+z$"), ("equilibrium", "equilibrium")]))
    ps, ms = read("pure_scan.csv"), read("mixed_scan.csv")
    out.append("\n## T9. Where is the high type's best response? (`pure_scan.csv`, `mixed_scan.csv`)\n\n")
    out.append(table(ps, [("r", "$r$"), ("schedules_with_entry", "schedules"), ("H_best_0", "best at 0"),
                          ("H_best_1", "best at 1"), ("H_best_interior", "interior best")]))
    out.append("\n")
    out.append(table(ms, [("r", "$r$"), ("schedules", "schedules (mixed profiles, holes)"),
                          ("H_interior_local_max", "interior local maxima")]))
    idc = read("identity_check.csv")
    out.append("\n## T10. Identity $\\mathbb E_{\\sigma_H}F_H=\\mathbb E_{\\sigma_L}F_L$ (`identity_check.csv`)\n\n")
    out.append(table(idc, [("r", "$r$"), ("sigma_H", "$\\sigma_H$"), ("sigma_L", "$\\sigma_L$"), ("entry", "$A$"),
                           ("E_sigmaH_F_H", "$\\mathbb E F_H$"), ("E_sigmaL_F_L", "$\\mathbb E F_L$"),
                           ("difference", "difference")], d=8))
    tie = read("tie_branch.csv")
    out.append("\n## T11. Preparation mixed at the indifferent atom (`tie_branch.csv`)\n\n")
    out.append(table(tie, [("r", "$r$"), ("n_r", "$n(r)$"), ("pi_plateau", "$\\pi$"), ("E", "$\\mathsf E$"),
                           ("E_formula_pi/(4tau)", "$\\pi/(4\\tau)$"), ("U_H", "$U_H$"), ("H_best", "H best"),
                           ("L_best", "L best")]))
    (HERE / "tables.md").write_text("".join(out))


if __name__ == "__main__":
    figure()
    tables()
